"""Add Offer model and update AvailabilitySlot

Revision ID: 3db25977c22c
Revises: bba41f562bcc
Create Date: 2025-11-25 07:11:22.534639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db25977c22c'
down_revision: Union[str, None] = 'bba41f562bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('max_bid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['availabilityslot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_id'), 'offer', ['id'], unique=False)
    op.add_column('availabilityslot', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('availabilityslot', sa.Column('auction_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('availabilityslot', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'availabilityslot', 'user', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availabilityslot', type_='foreignkey')
    op.drop_column('availabilityslot', 'winner_id')
    op.drop_column('availabilityslot', 'auction_end_time')
    op.drop_column('availabilityslot', 'current_price')
    op.drop_index(op.f('ix_offer_id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
