"""Add serial_number to machines

Revision ID: bba41f562bcc
Revises: 67fca4266a95
Create Date: 2025-11-24 18:39:41.301775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba41f562bcc'
down_revision: Union[str, None] = '67fca4266a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('serial_number', sa.String(), nullable=False))
    op.create_index(op.f('ix_machine_serial_number'), 'machine', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_serial_number'), table_name='machine')
    op.drop_column('machine', 'serial_number')
    # ### end Alembic commands ###
